/** The task catalogue is shared by the API, agent prompt and dashboard. No task publishes or sends mail. */
export const SEO_TASKS = {
  strategy: { agent: 'res', title: 'Editorial strategy', goal: 'Define the audience, business goal, original value, topic priorities and success measures. Identify YMYL and any conditional local, ecommerce, news or video requirements. Do not invent experience or a business model.', needsArticles: false },
  serp: { agent: 'res', title: 'SERP research', goal: 'Analyze the supplied DataForSEO SERP snapshot for this exact query, country and language. Distinguish observed result types from hypotheses about intent and content gaps. Never claim to have read full competitor pages from snippets.', needsArticles: false },
  architecture: { agent: 'arc', title: 'Site architecture', goal: 'Propose a topic and URL hierarchy, categories, navigation and crawlable links. Reuse existing slugs, avoid overlapping intent and network link schemes. Identify redirects needed before changing published URLs.', needsArticles: false },
  audit: { agent: 'seo', title: 'Content and SEO audit', goal: 'Audit supplied articles, metadata, sources, technical observations and AI search eligibility. List specific claims requiring source verification, unsupported first-hand experience and sensitive claims requiring expert review. Citations alone do not prove facts. Distinguish a local build check, a live HTTP observation, Google indexing and unmeasured CWV. No fixed title, description or word-count ranking limits.', needsArticles: true },
  links: { agent: 'lnk', title: 'Internal link proposals', goal: 'Find relevant contextual internal links and orphan pages from supplied article bodies and graph. Propose existing exact anchor text, from/to article IDs and a reason. No forced exact-match anchors, self-links, other-site links or automatic content changes.', needsArticles: true },
  analysis: { agent: 'ana', title: 'Performance analysis', goal: 'Interpret the supplied Search Console and GA4 snapshots, their date ranges, freshness and coverage. Prioritize declines, CTR opportunities and possible overlapping intent. Overlap is a hypothesis, not proof of cannibalization. Provide an action, owner and follow-up measure. Missing data is not zero performance. Do not fabricate conversions or separate AI search traffic.', needsArticles: false },
  refresh: { agent: 'seo', title: 'Content maintenance', goal: 'Prioritize articles to update using actual content age, source reliability and supplied performance. Specify claims to recheck, original improvements, intent overlap, consolidation and redirects where needed. Do not change dates to simulate freshness. Changes require article review and rebuild.', needsArticles: true },
  visual: { agent: 'gd', title: 'Infographic draft', goal: 'Create a concise, useful process infographic from supplied article evidence, in the site language. Return visual with title, alt and 2–6 steps {label,detail}. Use no invented numerical measurements. Include source URLs and uncertainties; human review is required. The server renders this as safe SVG, not model HTML.', needsArticles: true },
  pr: { agent: 'res', title: 'Digital PR and outreach draft', goal: 'Research relevant editorial publications or communities and propose an original asset worth citing. Use web retrieval for public opportunity URLs. Draft a personal outreach pitch in actions, never invent contacts, endorsements, links or proof of sending. No paid ranking links, automated backlink creation, reciprocal schemes or mass outreach. Sponsored links require appropriate qualification. Review and sending are separate human actions.', needsArticles: true },
} as const;
export type SeoTaskKind = keyof typeof SEO_TASKS;
export type SeoResult = { summary: string; findings: { title: string; detail: string; basis: 'observation' | 'proposal' | 'needs-verification' }[]; actions: { title: string; detail: string; priority: 'high' | 'medium' | 'low'; owner: string }[]; sources: { title: string; url: string }[]; limitations: string[]; links: { from: number; to: number; anchor: string; reason: string }[]; visual: { title: string; alt: string; steps: { label: string; detail: string }[] } | null };
export type SeoTaskWire = { engine?: 'openai-api' | 'codex-local' | ''; id: number; siteId: string; domain: string; kind: SeoTaskKind; agent: string; brief: string; status: 'queued' | 'work' | 'done' | 'failed'; result: SeoResult | null; error: string; createdAt: number; startedAt: number | null; finishedAt: number | null; tokens: number; costUsd: number; serviceCostUsd: number; reviewedAt: number | null; reviewedBy: string; context: string };
